$mainMod = SUPER
$terminal = kitty

monitor = eDP-1, 1920x1080@60, 0x0, 1
$fileManager = dolphin
$menu = hyprlauncher
$browser = zen-browser

exec-once = waybar
exec-once = wl-gammarelay-rs run
exec-once = busctl --user set-property rs.wl.gammarelay / rs.wl.gammarelay Gamma d 0.8
exec-once = busctl --user set-property rs.wl.gammarelay / rs.wl.gammarelay Temperature d 4500
exec-once = hyprshade on vibrance-strong

input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0
    numlock_by_default = true
    touchpad {
        natural_scroll = true
        scroll_factor = 1.0
    }
}

gestures {
    gesture = 3, horizontal, workspace
    workspace_swipe_distance = 300
    workspace_swipe_invert = false
    workspace_swipe_min_speed_to_force = 30
    workspace_swipe_cancel_ratio = 0.5
    workspace_swipe_direction_lock = true
    workspace_swipe_direction_lock_threshold = 10
    workspace_swipe_create_new = true
    workspace_swipe_forever = true
}

cursor {
    inactive_timeout = 3
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(00c8c8ee)
    col.inactive_border = rgba(45475a88)
    resize_on_border = true
    layout = dwindle
}

decoration {
    rounding = 10
    active_opacity = 0.95
    inactive_opacity = 0.85
    blur {
        enabled = true
        size = 4
        passes = 2
        vibrancy = 0.8
    }
}

# ---- APPS ----
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, T, exec, kitty tmux new-session -A -s main
bind = $mainMod, Q, killactive,
bind = $mainMod, B, exec, $browser
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, R, exec, $menu
bind = $mainMod, C, killactive,

# ---- SYSTEM ----
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, V, togglefloating,

# ---- MOVE FOCUS ----
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# ---- WORKSPACES ----
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# ---- AUDIO ----
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# ---- BRIGHTNESS ----
bindel = , XF86MonBrightnessUp, exec, brightnessctl s +5%
bindel = , XF86MonBrightnessDown, exec, brightnessctl s 5%-

# ---- MOVE WINDOW TO WORKSPACE ----
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
